# yaml-language-server: $schema=https://raw.githubusercontent.com/microsoft/winget-cli/master/schemas/JSON/manifests/v1.10.0/manifest.version.1.10.0.json

PackageIdentifier: SiarheiKuchuk.BUtil
PackageVersion: 2025.10.13.1
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0

