# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.FtpsServer
PackageVersion: 2026.09.35
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
ProductCode: FTPS Server
ReleaseDate: 2026-09-35
Installers:
- InstallerUrl: https://github.com/drweb86/dotnet-ftps-server/releases/download/2026.09.35/ftpsserver_2026.09.35_windows_setup.exe
  Platform:
    - Windows.Desktop
  Architecture: arm64
  InstallerSha256: 40CB181609A8698FD582DF43147B4D6E43B51D58C64BC9F5F7056876CB5D9F91
  Scope: user
  InstallerSwitches:
    Custom: /CLOSEAPPLICATIONS /CURRENTUSER /S
- InstallerUrl: https://github.com/drweb86/dotnet-ftps-server/releases/download/2026.09.35/ftpsserver_2026.09.35_windows_setup.exe
  Platform:
    - Windows.Desktop
  Architecture: arm64
  InstallerSha256: 40CB181609A8698FD582DF43147B4D6E43B51D58C64BC9F5F7056876CB5D9F91
  Scope: machine
  InstallerSwitches:
    Custom: /CLOSEAPPLICATIONS /ALLUSERS /S
  ElevationRequirement: elevationRequired
- InstallerUrl: https://github.com/drweb86/dotnet-ftps-server/releases/download/2026.09.35/ftpsserver_2026.09.35_windows_setup.exe
  Platform:
    - Windows.Desktop
  Architecture: x64
  InstallerSha256: 40CB181609A8698FD582DF43147B4D6E43B51D58C64BC9F5F7056876CB5D9F91
  Scope: user
  InstallerSwitches:
    Custom: /CLOSEAPPLICATIONS /CURRENTUSER /S
- InstallerUrl: https://github.com/drweb86/dotnet-ftps-server/releases/download/2026.09.35/ftpsserver_2026.09.35_windows_setup.exe
  Platform:
    - Windows.Desktop
  Architecture: x64
  InstallerSha256: 40CB181609A8698FD582DF43147B4D6E43B51D58C64BC9F5F7056876CB5D9F91
  Scope: machine
  InstallerSwitches:
    Custom: /CLOSEAPPLICATIONS /ALLUSERS /S
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
