# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: ur-PK
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "پہلے وہ آڈیو آلات منتخب کریں جو کانفرنس سافٹ ویئر استعمال کرتا ہے۔"
Description: |-
  کانفرنس آڈیو ریکارڈر

  پہلے وہ آڈیو آلات منتخب کریں جو کانفرنس سافٹ ویئر استعمال کرتا ہے۔

  پھر آزمائشی ریکارڈنگ کریں۔ اگر گونج سنائی دے تو مائیکروفون اسپیکر سن رہا ہے۔ اسپیکر ریکارڈنگ بند کریں یا ہیڈ فون استعمال کریں۔

  میٹنگ شروع ہوتے ہی ریکارڈنگ شروع کریں اور ختم ہونے پر روک دیں۔

  MP3 فائل ریکارڈنگ فولڈر میں محفوظ ہوتی ہے۔ "ریکارڈنگ دیکھیں" وہ فولڈر کھولتا ہے۔
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
