# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: el-GR
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "Πρώτα επιλέξτε τις συσκευές ήχου που χρησιμοποιεί το πρόγραμμα συνδιάσκεψης."
Description: |-
  Εγγραφή ήχου συνδιάσκεψης

  Πρώτα επιλέξτε τις συσκευές ήχου που χρησιμοποιεί το πρόγραμμα συνδιάσκεψης.

  Έπειτα κάντε μια δοκιμαστική εγγραφή. Αν ακούτε ηχώ, το μικρόφωνο ακούει το ηχείο. Απενεργοποιήστε την εγγραφή του ηχείου ή χρησιμοποιήστε ακουστικά.

  Στην αρχή της συνάντησης ξεκινήστε την εγγραφή και σταματήστε την στο τέλος.

  Το αρχείο MP3 αποθηκεύεται στον φάκελο εγγραφών. Το κουμπί «Προβολή εγγραφών» τον ανοίγει.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
