# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: nl-NL
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "Kies eerst de audioapparaten die het conferentieprogramma gebruikt dat u wilt opnemen."
Description: |-
  Conferentie-audiorecorder

  Kies eerst de audioapparaten die het conferentieprogramma gebruikt dat u wilt opnemen.

  Maak daarna een testopname. Als u echo hoort, vangt de microfoon de luidspreker op. Schakel de luidsprekeropname uit of gebruik een hoofdtelefoon.

  Start de opname aan het begin van de vergadering en stop wanneer de vergadering eindigt.

  Het MP3-bestand komt in de map met opnamen. De knop 'Opnamen bekijken' opent die map.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
