# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: hi-IN
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "पहले वे ऑडियो उपकरण चुनें जिनका उपयोग कॉन्फ़्रेंस सॉफ़्टवेयर करता है।"
Description: |-
  कॉन्फ़्रेंस ऑडियो रिकॉर्डर

  पहले वे ऑडियो उपकरण चुनें जिनका उपयोग कॉन्फ़्रेंस सॉफ़्टवेयर करता है।

  फिर एक परीक्षण रिकॉर्डिंग करें। यदि प्रतिध्वनि सुनाई दे, तो माइक्रोफ़ोन स्पीकर सुन रहा है। स्पीकर रिकॉर्डिंग बंद करें या हेडफ़ोन का उपयोग करें।

  मीटिंग शुरू होते ही रिकॉर्डिंग शुरू करें और समाप्त होने पर रोकें।

  MP3 फ़ाइल रिकॉर्डिंग फ़ोल्डर में सहेजी जाती है। "रिकॉर्डिंग देखें" वह फ़ोल्डर खोलता है।
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
