# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: ps-AF
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "لومړی هغه غږیز وسایل وټاکئ چې د غونډې پروګرام یې کاروي."
Description: |-
  د غونډې غږ ثبتوونکی

  لومړی هغه غږیز وسایل وټاکئ چې د غونډې پروګرام یې کاروي.

  بیا آزمویښتي ثبت وکړئ. که غږ تکرار اورئ، مایکروفون سپیکر اوري. د سپیکر ثبت بند کړئ یا هیډفون وکاروئ.

  کله چې ناسته پیل شي ثبت پیل کړئ او کله چې پای ته ورسېږي یې ودروئ.

  د MP3 فایل د ثبتونو په فولډر کې ساتل کېږي. "ثبتونه وګورئ" هغه فولډر پرانیزي.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
