# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: th-TH
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "ก่อนอื่น เลือกอุปกรณ์เสียงที่โปรแกรมประชุมใช้งาน"
Description: |-
  โปรแกรมบันทึกเสียงการประชุม

  ก่อนอื่น เลือกอุปกรณ์เสียงที่โปรแกรมประชุมใช้งาน

  จากนั้นทดลองบันทึก หากได้ยินเสียงสะท้อน แสดงว่าไมโครโฟนได้ยินลำโพง ให้ปิดการบันทึกลำโพงหรือใช้หูฟัง

  เมื่อการประชุมเริ่ม ให้เริ่มบันทึก และหยุดเมื่อการประชุมจบ

  ไฟล์ MP3 จะอยู่ในโฟลเดอร์บันทึก ปุ่ม "ดูไฟล์บันทึก" จะเปิดโฟลเดอร์นั้น
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
