# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: mr-IN
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "आधी परिषद सॉफ्टवेअर वापरत असलेली ऑडिओ साधने निवडा."
Description: |-
  परिषद ऑडिओ रेकॉर्डर

  आधी परिषद सॉफ्टवेअर वापरत असलेली ऑडिओ साधने निवडा.

  नंतर चाचणी रेकॉर्डिंग करा. प्रतिध्वनी ऐकू आल्यास मायक स्पीकर ऐकत आहे. स्पीकर रेकॉर्डिंग बंद करा किंवा हेडफोन वापरा.

  बैठक सुरू होताच रेकॉर्डिंग सुरू करा आणि संपल्यावर थांबवा.

  MP3 फाइल रेकॉर्डिंग फोल्डरमध्ये जतन होते. "रेकॉर्डिंग पहा" ते फोल्डर उघडते.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
