# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: te-IN
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "ముందు సమావేశ సాఫ్ట్‌వేర్ ఉపయోగించే ఆడియో పరికరాలను ఎంచుకోండి."
Description: |-
  సమావేశ ఆడియో రికార్డర్

  ముందు సమావేశ సాఫ్ట్‌వేర్ ఉపయోగించే ఆడియో పరికరాలను ఎంచుకోండి.

  తర్వాత పరీక్ష రికార్డింగ్ చేయండి. ప్రతిధ్వని వినిపిస్తే మైక్రోఫోన్ స్పీకర్‌ను వింటోంది. స్పీకర్ రికార్డింగ్ ఆఫ్ చేయండి లేదా హెడ్‌ఫోన్ వాడండి.

  సమావేశం మొదలైనప్పుడు రికార్డింగ్ ప్రారంభించి, అయిపోయాక ఆపండి.

  MP3 ఫైలు రికార్డింగ్‌ల ఫోల్డర్‌లో సేవ్ అవుతుంది. "రికార్డింగ్‌లు చూడండి" ఆ ఫోల్డర్‌ను తెరుస్తుంది.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
