# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: it-IT
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "Per prima cosa seleziona i dispositivi audio usati dal programma di conferenza che vuoi registrare."
Description: |-
  Registratore audio per conferenze

  Per prima cosa seleziona i dispositivi audio usati dal programma di conferenza che vuoi registrare.

  Poi fai una registrazione di prova. Se senti l'eco, il microfono sente l'altoparlante. Disattiva la registrazione dell'altoparlante oppure usa le cuffie.

  All'inizio della riunione avvia la registrazione e fermala quando la riunione finisce.

  Il file MP3 viene salvato nella cartella delle registrazioni. Il pulsante «Vedi registrazioni» la apre.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
