# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: hr-HR
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "Najprije odaberite audionaprave koje koristi program za konferencije."
Description: |-
  Snimač zvuka konferencija

  Najprije odaberite audionaprave koje koristi program za konferencije.

  Zatim napravite probno snimanje. Ako čujete jeku, mikrofon čuje zvučnik. Isključite snimanje zvučnika ili koristite slušalice.

  Na početku sastanka pokrenite snimanje i zaustavite ga na kraju.

  MP3 datoteka sprema se u mapu snimki. Gumb „Prikaži snimke“ otvara tu mapu.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
