# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: pt-BR
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "Primeiro, selecione os dispositivos de áudio usados no software de conferência que você deseja gravar."
Description: |-
  Gravador de áudio de conferência

  Primeiro, selecione os dispositivos de áudio usados no software de conferência que você deseja gravar.

  Segundo, faça uma gravação de teste. Se você ouvir eco na gravação, provavelmente o microfone está captando o áudio do alto-falante. Nesse caso, tente desabilitar a gravação do alto-falante ou use fones de ouvido.

  Terceiro, clique em iniciar gravação no início de uma reunião e pare quando a reunião terminar.

  O arquivo MP3 com as gravações será salvo na pasta de gravações. Clique no botão 'Ver gravações' para abri-la.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
