# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: hu-HU
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "Először válassza ki a konferenciaprogram által használt hangeszközöket."
Description: |-
  Konferencia-hangrögzítő

  Először válassza ki a konferenciaprogram által használt hangeszközöket.

  Ezután készítsen próbarögzítést. Ha visszhangot hall, a mikrofon a hangszórót veszi. Kapcsolja ki a hangszóró rögzítését, vagy használjon fejhallgatót.

  A találkozó elején indítsa el a rögzítést, és a végén állítsa le.

  Az MP3 a felvételek mappájába kerül. A „Felvételek megtekintése” gomb megnyitja.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
