# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: bn-IN
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "প্রথমে কনফারেন্স সফটওয়্যার যে অডিও ডিভাইস ব্যবহার করে সেগুলো বেছে নিন।"
Description: |-
  কনফারেন্স অডিও রেকর্ডার

  প্রথমে কনফারেন্স সফটওয়্যার যে অডিও ডিভাইস ব্যবহার করে সেগুলো বেছে নিন।

  তারপর একটি পরীক্ষামূলক রেকর্ডিং করুন। প্রতিধ্বনি শুনলে মাইক্রোফোন স্পিকার শুনছে। স্পিকার রেকর্ডিং বন্ধ করুন বা হেডফোন ব্যবহার করুন।

  মিটিং শুরু হলে রেকর্ডিং শুরু করুন এবং শেষ হলে থামান।

  MP3 ফাইল রেকর্ডিং ফোল্ডারে সেভ হয়। "রেকর্ডিং দেখুন" সেই ফোল্ডার খোলে।
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
