# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: es-ES
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "Primero, seleccione los dispositivos de audio que se utilizan en el software de conferencias que desea grabar."
Description: |-
  Grabadora de audio de conferencias

  Primero, seleccione los dispositivos de audio que se utilizan en el software de conferencias que desea grabar.

  Segundo, realice una grabación de prueba. Si escucha eco en la grabación, es probable que el micrófono escuche su altavoz. En este caso, intente deshabilitar la grabación del altavoz o use auriculares.

  Tercero, haga clic en iniciar grabación al comienzo de una reunión y deténgala cuando termine la reunión.

  El archivo MP3 con las grabaciones se guardará en la carpeta de grabaciones. Haga clic en el botón 'Ver grabaciones' para abrirla.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
