# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: de-DE
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "Wählen Sie zunächst die Audiogeräte aus, die in der Konferenzsoftware verwendet werden, die Sie aufzeichnen möchten."
Description: |-
  Konferenz-Audiorekorder

  Wählen Sie zunächst die Audiogeräte aus, die in der Konferenzsoftware verwendet werden, die Sie aufzeichnen möchten.

  Führen Sie zweitens eine Testaufnahme durch. Wenn Sie ein Echo in der Aufnahme hören, hört das Mikrofon wahrscheinlich Ihren Lautsprecher. Versuchen Sie in diesem Fall, die Aufnahme des Lautsprechers zu deaktivieren oder verwenden Sie Kopfhörer.

  Klicken Sie drittens zu Beginn eines Meetings auf Aufnahme starten und stoppen Sie sie, wenn das Meeting endet.

  Die MP3-Datei mit den Aufnahmen wird im Aufnahmeordner gespeichert. Klicken Sie auf die Schaltfläche „Aufnahmen anzeigen“, um dorthin zu navigieren.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
