# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: uz-UZ
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "Avval konferensiya dasturi ishlatadigan audio qurilmalarni tanlang."
Description: |-
  Konferensiya audio yozuvchisi

  Avval konferensiya dasturi ishlatadigan audio qurilmalarni tanlang.

  So‘ng sinov yozuvi oling. Aks-sado eshitsangiz, mikrofon karnayni eshitayapti. Karnay yozuvini o‘chiring yoki quloqchin ishlating.

  Uchrashuv boshlanganda yozishni boshlang va tugaganda to‘xtating.

  MP3 fayl yozuvlar jildiga saqlanadi. «Yozuvlarni ko‘rish» tugmasi uni ochadi.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
