# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: ja-JP
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "まず、録音したい会議ソフトウェアで使用されているオーディオデバイスを選択してください。"
Description: |-
  会議音声レコーダー

  まず、録音したい会議ソフトウェアで使用されているオーディオデバイスを選択してください。

  次に、テスト録音を実行してください。録音でエコーが聞こえる場合は、マイクがスピーカーの音を拾っている可能性があります。この場合、スピーカーの録音を無効にするか、ヘッドフォンを使用してください。

  会議の開始時に録音開始をクリックし、会議が終了したら停止してください。

  録音されたMP3ファイルは録音フォルダに保存されます。「録音を表示」ボタンをクリックしてフォルダに移動してください。
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
