# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
ProductCode: ConferenceAudioRecorder
ReleaseDate: 2026-09-26
Installers:
- InstallerUrl: https://github.com/drweb86/conference-audio-recorder/releases/download/2026.09.26/conference-audio-recorder_2026.09.26_windows_setup.exe
  Platform:
    - Windows.Desktop
  Architecture: arm64
  InstallerSha256: 1EDB5A4442411A4E6FDCD9F392652CC48FB45400573B8A973C3A176872E749B5
  Scope: user
  InstallerSwitches:
    Custom: /CURRENTUSER /S
- InstallerUrl: https://github.com/drweb86/conference-audio-recorder/releases/download/2026.09.26/conference-audio-recorder_2026.09.26_windows_setup.exe
  Platform:
    - Windows.Desktop
  Architecture: arm64
  InstallerSha256: 1EDB5A4442411A4E6FDCD9F392652CC48FB45400573B8A973C3A176872E749B5
  Scope: machine
  InstallerSwitches:
    Custom: /ALLUSERS /S
  ElevationRequirement: elevationRequired
- InstallerUrl: https://github.com/drweb86/conference-audio-recorder/releases/download/2026.09.26/conference-audio-recorder_2026.09.26_windows_setup.exe
  Platform:
    - Windows.Desktop
  Architecture: x64
  InstallerSha256: 1EDB5A4442411A4E6FDCD9F392652CC48FB45400573B8A973C3A176872E749B5
  Scope: user
  InstallerSwitches:
    Custom: /CURRENTUSER /S
- InstallerUrl: https://github.com/drweb86/conference-audio-recorder/releases/download/2026.09.26/conference-audio-recorder_2026.09.26_windows_setup.exe
  Platform:
    - Windows.Desktop
  Architecture: x64
  InstallerSha256: 1EDB5A4442411A4E6FDCD9F392652CC48FB45400573B8A973C3A176872E749B5
  Scope: machine
  InstallerSwitches:
    Custom: /ALLUSERS /S
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
