# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: vi-VN
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "Trước hết, hãy chọn thiết bị âm thanh mà phần mềm họp đang dùng."
Description: |-
  Trình ghi âm hội nghị

  Trước hết, hãy chọn thiết bị âm thanh mà phần mềm họp đang dùng.

  Sau đó hãy ghi thử. Nếu nghe tiếng vọng, micro đang thu loa. Hãy tắt ghi loa hoặc dùng tai nghe.

  Khi cuộc họp bắt đầu thì bắt đầu ghi, và dừng khi cuộc họp kết thúc.

  Tệp MP3 được lưu trong thư mục bản ghi. Nút "Xem bản ghi" sẽ mở thư mục đó.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
