# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: SiarheiKuchuk.ConferenceAudioRecorder
PackageVersion: 2026.09.26
PackageLocale: ko-KR
Publisher: Siarhei Kuchuk
PublisherUrl: https://github.com/drweb86
PublisherSupportUrl: https://github.com/drweb86/conference-audio-recorder/issues
PrivacyUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/Privacy%20Policy.md
Author: Siarhei Kuchuk
PackageName: Conference Audio Recorder
PackageUrl: https://github.com/drweb86/conference-audio-recorder
License: CC0-1.0
LicenseUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
Copyright: 2022-2026 Siarhei Kuchuk
CopyrightUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/LICENSE
ShortDescription: "먼저, 녹음하려는 회의 소프트웨어에서 사용하는 오디오 장치를 선택하세요."
Description: |-
  회의 오디오 녹음기

  먼저, 녹음하려는 회의 소프트웨어에서 사용하는 오디오 장치를 선택하세요.

  둘째, 테스트 녹음을 수행하세요. 녹음에서 에코가 들리면 마이크가 스피커 소리를 듣고 있을 가능성이 있습니다. 이 경우 스피커 녹음을 비활성화하거나 헤드폰을 사용하세요.

  셋째, 회의 시작 시 녹음 시작을 클릭하고 회의가 끝나면 중지하세요.

  녹음된 MP3 파일은 녹음 폴더에 저장됩니다. '녹음 보기' 버튼을 클릭하여 해당 폴더로 이동하세요.
Moniker: conference-audio-recorder
Tags:
- "conference recorder"
- "microphone speaker"
- "mp3"
- "teams viber skype"
ReleaseNotesUrl: https://raw.githubusercontent.com/drweb86/conference-audio-recorder/refs/heads/main/CHANGELOG.md
ManifestType: locale
ManifestVersion: 1.12.0
